#!/bin/bash
cd "$(dirname -- "$(readlink -fn -- "${0}")")"

# ./update_external_sources.sh
# cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DBUILD_LOADER=OFF -DBUILD_TESTS=OFF -DBUILD_LAYERS=ON -DBUILD_DEMOS=OFF -DBUILD_VKJSON=OFF -DBUILD_ICD=OFF
# cd build
# make VERBOSE=1

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers

cp -r SPIRV "$HOME"/Vulkan-LoaderAndValidationLayers/build
cp -r spirv-tools "$HOME"/Vulkan-LoaderAndValidationLayers/build
cp libSPIRV-Tools.a "$HOME"/Vulkan-LoaderAndValidationLayers/build
cp libSPIRV-Tools-opt.a "$HOME"/Vulkan-LoaderAndValidationLayers/build

cd "$HOME"/Vulkan-LoaderAndValidationLayers/build

echo '#pragma once' > spirv_tools_commit_id.h
echo '#define SPIRV_TOOLS_COMMIT_ID "5834719fc17d4735fce0102738b87b70255cfd5f"' >> spirv_tools_commit_id.h

python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_enum_string_helper.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_struct_size_helper.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_struct_size_helper.c
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_safe_struct.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_safe_struct.cpp
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_object_types.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_layer_dispatch_table.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_dispatch_table_helper.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_extension_helper.h
python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml vk_typemap_helper.h

cd "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers

c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_utils_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_config.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_config.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_utils_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_extension_utils.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_extension_utils.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_utils_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_utils.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_utils.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_utils_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_format_utils.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_format_utils.cpp
c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -shared -Wl,-soname,libVkLayer_utils.so -o libVkLayer_utils.so vk_layer_config.cpp.o vk_layer_extension_utils.cpp.o vk_layer_utils.cpp.o vk_format_utils.cpp.o 

python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml parameter_validation.cpp

c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_parameter_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o parameter_validation.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/parameter_validation.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_parameter_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o parameter_validation_utils.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/parameter_validation_utils.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_parameter_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_table.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_table.cpp
c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -Wl,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_parameter_validation.so -o libVkLayer_parameter_validation.so parameter_validation.cpp.o parameter_validation_utils.cpp.o vk_layer_table.cpp.o -Wl,-rpath,"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers: libVkLayer_utils.so 

python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml unique_objects_wrappers.h

c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_unique_objects_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o unique_objects.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/unique_objects.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_unique_objects_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_table.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_table.cpp
c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -Wl,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_unique_objects.so -o libVkLayer_unique_objects.so unique_objects.cpp.o vk_layer_table.cpp.o -Wl,-rpath,"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers: libVkLayer_utils.so 

python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml thread_check.h

c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_threading_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o threading.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/threading.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_threading_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_table.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_table.cpp
c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -Wl,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_threading.so -o libVkLayer_threading.so threading.cpp.o vk_layer_table.cpp.o -Wl,-rpath,"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers: libVkLayer_utils.so 

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_threading.json

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
cp "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_threading.json "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
sed -i -e "/\"library_path\":/s\$./libVkLayer\$libVkLayer\$" "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json/VkLayer_threading.json

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_parameter_validation.json

python3 "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py -registry "$HOME"/Vulkan-LoaderAndValidationLayers/scripts/vk.xml object_tracker.cpp

c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_object_tracker_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o object_tracker.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/object_tracker.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_object_tracker_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o object_tracker_utils.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/object_tracker_utils.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_object_tracker_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_table.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_table.cpp
c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -Wl,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_object_tracker.so -o libVkLayer_object_tracker.so object_tracker.cpp.o object_tracker_utils.cpp.o vk_layer_table.cpp.o -Wl,-rpath,"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers: libVkLayer_utils.so 

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_object_tracker.json

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
cp "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_standard_validation.json "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
sed -i -e "/\"library_path\":/s\$./libVkLayer\$libVkLayer\$" "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json/VkLayer_standard_validation.json

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_device_simulation.json

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/libVkLayer_device_simulation.so

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_unique_objects.json

c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/spirv-tools/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o core_validation.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/core_validation.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/spirv-tools/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o vk_layer_table.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_layer_table.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/spirv-tools/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o descriptor_sets.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/descriptor_sets.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/spirv-tools/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o buffer_validation.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/buffer_validation.cpp
c++ -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/spirv-tools/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o shader_validation.cpp.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/shader_validation.cpp
cc  -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I"$HOME"/Vulkan-LoaderAndValidationLayers/include -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../loader -I"$HOME"/Vulkan-LoaderAndValidationLayers/layers/../include/vulkan -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers -I"$HOME"/Vulkan-LoaderAndValidationLayers/build -I"$HOME"/Vulkan-LoaderAndValidationLayers/build/spirv-tools/include -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC -o xxhash.c.o -c "$HOME"/Vulkan-LoaderAndValidationLayers/layers/xxhash.c
c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -Wl,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_core_validation.so -o libVkLayer_core_validation.so core_validation.cpp.o vk_layer_table.cpp.o descriptor_sets.cpp.o buffer_validation.cpp.o shader_validation.cpp.o xxhash.c.o -Wl,-rpath,"$HOME"/Vulkan-LoaderAndValidationLayers/build/layers: libVkLayer_utils.so "$HOME"/Vulkan-LoaderAndValidationLayers/build/libSPIRV-Tools-opt.a "$HOME"/Vulkan-LoaderAndValidationLayers/build/libSPIRV-Tools.a

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_core_validation.json

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_standard_validation.json

ln -sf "$HOME"/Vulkan-LoaderAndValidationLayers/layers/vk_validation_error_messages.h

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
cp "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_core_validation.json "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
sed -i -e "/\"library_path\":/s\$./libVkLayer\$libVkLayer\$" "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json/VkLayer_core_validation.json

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
cp "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_parameter_validation.json "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
sed -i -e "/\"library_path\":/s\$./libVkLayer\$libVkLayer\$" "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json/VkLayer_parameter_validation.json

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
cp "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_object_tracker.json "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
sed -i -e "/\"library_path\":/s\$./libVkLayer\$libVkLayer\$" "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json/VkLayer_object_tracker.json

mkdir -p "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
cp "$HOME"/Vulkan-LoaderAndValidationLayers/layers/linux/VkLayer_unique_objects.json "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json
sed -i -e "/\"library_path\":/s\$./libVkLayer\$libVkLayer\$" "$HOME"/Vulkan-LoaderAndValidationLayers/build/layers/staging-json/VkLayer_unique_objects.json
